development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  # url: redis://localhost:6379/1
  url: redis://aws-production.5fsrj3kfbx.us-west-2.elasticbeanstalk.com:6379
  # channel_prefix: regency_app_production